### ISSUE TITLE
Review CSS variable implementation for font-size, line-height, font-family

### ISSUE THREAD

**Issue by substrae** [hydrogen-css/hydrogen#150]
# Requirements

In relation to [this spike regarding Infusion](https://github.com/GCTC-NTGC/gc-accessibility-passport/issues/123), the variables used for `font-size`, `line-height`, and `font-family` will need to be appropriately used so that they can be manipulated by JavaScript for accessibility purposes.

Might have to create a separate space variable that isn't changed when the line-height one is...

**Comment by JoshBeveridge** [comment]
Concept:
- For manipulating font size, change `--h2BaseFontSize`
- For manipulating paragraph line height, change `--h2BaseLineHeight`
- For changing font family, change the relevant family variable (e.g. if you've set a key as `sans` for your sans-serif font, change `--h2FontFamilySans`
