### ISSUE TITLE
Allow control of log output

### ISSUE THREAD

**Issue by mnigh** [hydrogen-css/hydrogen#204]
Allow control of log output, similar to webpack:

> The stats option lets you precisely control what bundle information gets displayed. This can be a nice middle ground if you don't want to use `quiet` or `noInfo` because you want some bundle information, but not all of it.

https://webpack.js.org/configuration/stats/

**Comment by substrae** [comment]
Resolved in https://github.com/hydrogen-css/hydrogen/pull/205 :)
