### ISSUE TITLE
Error codes for build process

### ISSUE THREAD

**Issue by petertgiles** [hydrogen-css/hydrogen#270]
## ✨ Feature

CLI commands often exit with a code to indicate the status of the command.  Usually 0 is _success_ and any non-zero code is _failure_.

## 🕵️ Details

It looks like this is the page to check for node.   https://nodejs.org/api/process.html#process_process_exit_code
> Rather than calling process.exit() directly, the code should set the process.exitCode and allow the process to exit naturally by avoiding scheduling any additional work for the event loop.

## 📸 Screenshot

![image](https://github.com/hydrogen-css/hydrogen/assets/8978655/a65406d0-ac65-48fa-b76b-b05977b5e004)

## 🙋‍♀️ Proposed Implementation

I'd suggest starting simple with just:
| Status | Description     |
|--------|-----------------|
| 0      | Success         |
| 1      | General Error |

## ✅ Acceptance Criteria

- [ ] Running h2-build with no errors returns an exit code of 0
- [ ] Running h2-build with any kind of error returns a non-zero exit code

**Comment by vd1992** [comment]
A potential example of `process.exit` implementation

![image](https://github.com/hydrogen-css/hydrogen/assets/40485260/d2caa2c0-e3e6-4e4b-995c-a6c00dfdde94)

**Comment by substrae** [comment]
@petertgiles @vd1992 

Do you mind taking a peek at https://github.com/hydrogen-css/hydrogen/pull/272/commits/93407d19e25eac9a66216ec1768d75823946bca9 to see if this approach addresses your ask? It sounds like the Node will end the process automatically based on the documentation, but I'm not sure if that means the initial parent process or the child Hydrogen process or both.

**Comment by petertgiles** [comment]
Nice!  When running h2-build directly I see the expected exit codes.
![image](https://github.com/hydrogen-css/hydrogen/assets/8978655/0716e0c4-ebd3-4808-8384-392723d5e53e)
As a side bonus - it actually kills the Webpack build so it knocks that issue off our board, too!

**Comment by substrae** [comment]
@petertgiles

Awesome! Thanks for checking for me. I'll hopefully have this release out after a bit of testing.

**Comment by vd1992** [comment]
Awesome stuff you two!
