### ISSUE TITLE
Remove unsed dependencies

### ISSUE THREAD

**Issue by patcon** [hydrogen-css/hydrogen#65]
Re-ticketed from #64 

I ran `depcheck` CLI on the repo. It's sometimes a bit overeager, but it picked up on these "unused" packages:

```
Unused dependencies
* browser-sync
* browserslist
* cssnano-preset-lite
* gulp-concat
* gulp-gzip
* gulp-rename
* merge-stream
* normalize.css
* vinyl-source-stream
* yargs
Unused devDependencies
* gulp-purgecss
```

Are there any here that could be removed without any loss (in DX or functionality)?

**Comment by JoshBeveridge** [comment]
Awesome, thanks for this @patcon 

Some of these were false positives, but I'm prepping `1.2.0` [for release soon](https://github.com/hydrogen-design-system/hydrogen.css/pull/41) and I'll take a look at getting the proper ones removed.

**Comment by patcon** [comment]
k sounds good! I'll build my docker experiments from my fork until then

Thanks!
